[package]
name = "yabridgectl"
version = "0.1.0"
authors = ["Robbert van der Helm <mail@robbertvanderhelm.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "0.7.13"
clap = "3.0.0-beta.1"
rayon = "1.3.1"
toml = "0.5.6"
